- project:
    templates:
      - check-requirements
      - publish-openstack-docs-pti
      - tempest-plugin-jobs
    check:
      jobs:
        # NOTE(dtantsur): keep N-3 and older non-voting for these jobs.
        - ironic-standalone
        - ironic-standalone-2024.1
        - ironic-standalone-2023.2
        - ironic-standalone-2023.1:
            voting: false
        - ironic-tempest-functional-python3
        - ironic-tempest-functional-python3-2024.1
        - ironic-tempest-functional-python3-2023.2:
            voting: false
        - ironic-tempest-functional-rbac-scope-enforced
        - ironic-tempest-functional-rbac-scope-enforced-2024.1
        - ironic-tempest-functional-rbac-scope-enforced-2023.2
        # Enable these *once* we have the policy fix backported
        # for making own node changes.
        # - ironic-tempest-functional-rbac-scope-enforced-2023.1
        - ironic-inspector-tempest
        - ironic-inspector-tempest-2024.1
        - ironic-inspector-tempest-2023.2
        - ironic-inspector-tempest-2023.1:
            voting: false
        - ironic-standalone-anaconda
        - ironic-standalone-anaconda-2024.1
        - ironic-standalone-anaconda-2023.2
        - ironic-standalone-anaconda-2023.1:
            voting: false
        - ironic-standalone-redfish
        - ironic-standalone-redfish-2024.1
        - ironic-standalone-redfish-2023.2
        - ironic-standalone-redfish-2023.1:
            voting: false
        # NOTE(dtantsur): these jobs cover rarely changed tests and are quite
        # unstable, so keep them non-voting.
        - ironic-tempest-ipa-wholedisk-direct-tinyipa-multinode:
            voting: false
        - ironic-tempest-ipa-wholedisk-direct-tinyipa-multinode-2024.1:
            voting: false
        - ironic-tempest-ipa-wholedisk-direct-tinyipa-multinode-2023.2:
            voting: false
        - ironic-tempest-ipa-wholedisk-direct-tinyipa-multinode-2023.1:
            voting: false
        - ironic-inspector-tempest-discovery
        - ironic-inspector-tempest-discovery-2024.1
        - ironic-inspector-tempest-discovery-2023.2
        - ironic-inspector-tempest-discovery-2023.1:
            voting: false
    gate:
      jobs:
        - ironic-standalone
        - ironic-standalone-2024.1
        - ironic-standalone-2023.2
        - ironic-tempest-functional-python3
        - ironic-tempest-functional-python3-2024.1
        - ironic-tempest-functional-python3-2023.2
        - ironic-tempest-functional-rbac-scope-enforced-2024.1
        - ironic-tempest-functional-rbac-scope-enforced-2023.2
        - ironic-tempest-functional-rbac-scope-enforced
        - ironic-inspector-tempest
        - ironic-inspector-tempest-2024.1
        - ironic-inspector-tempest-2023.2
        - ironic-inspector-tempest-rbac-scope-enforced
        - ironic-inspector-tempest-rbac-scope-enforced-2024.1
        - ironic-inspector-tempest-rbac-scope-enforced-2023.2
        - ironic-standalone-redfish
        - ironic-standalone-redfish-2024.1
        - ironic-standalone-redfish-2023.2
        - ironic-inspector-tempest-discovery
